### ISSUE TITLE
Getting error msg while importing - 'from suds.client import Client' on Python 2.6

### ISSUE THREAD

**Issue by abhi7878** [suds-community/suds#68]
>>> from suds.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python2.6/site-packages/suds/client.py", line 23, in <module>
    import suds.bindings.binding
  File "/usr/local/lib64/python2.6/site-packages/suds/bindings/binding.py", line 23, in <module>
    from suds.sax.document import Document
  File "/usr/local/lib64/python2.6/site-packages/suds/sax/document.py", line 23, in <module>
    from suds.sax.element import Element
  File "/usr/local/lib64/python2.6/site-packages/suds/sax/element.py", line 23, in <module>
    from suds.sax.text import Text
  File "/usr/local/lib64/python2.6/site-packages/suds/sax/text.py", line 25, in <module>
    class Text(str):
TypeError: Error when calling the metaclass bases
    nonempty __slots__ not supported for subtype of 'str'

**Comment by phillbaker** [comment]
Hello, Python 2.6 is not a currently supported version of Python for this package. Please see https://github.com/suds-community/suds#python-support.

If you can reproduce this on other versions of python, please confirm the package and version of suds-community that you're using. This issue will be closed in a few days unless more information is provided.

**Comment by abhi7878** [comment]
Thanks for the update, tried on Python3 it's working fine.
